"""Add guests count

Revision ID: a5f176fc90ad
Revises: e09f82e1c2ee
Create Date: 2026-02-13 19:05:00.728318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5f176fc90ad'
down_revision: Union[str, Sequence[str], None] = 'e09f82e1c2ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('guests_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'guests_count')
    # ### end Alembic commands ###
